[build]
  command = "npm install && npm run build"
  functions = "functions"

[[redirects]]
  from = "/* url=:url"
  to = "/.netlify/functions/server/:url:splat"
  status = 200
  #query = {url = ":url"}